# Generated by Django 5.1.14 on 2025-11-09 19:29

import django.core.validators
import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cpf',
            field=encrypted_model_fields.fields.EncryptedCharField(help_text='Digite um CPF válido (com ou sem pontuação).', unique=True, validators=[django.core.validators.RegexValidator(message='Digite um CPF válido (com ou sem pontuação).', regex='^(\\d{3}\\.?\\d{3}\\.?\\d{3}-?\\d{2})$')]),
        ),
    ]
