# Generated by Django 5.1.14 on 2025-11-12 01:58

import django.core.validators
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_alter_perfil_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cpf',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Digite um CPF válido (com ou sem pontuação).', null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Digite um CPF válido (com ou sem pontuação).', regex='^(\\d{3}\\.?\\d{3}\\.?\\d{3}-?\\d{2})$')]),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='genero',
            field=models.CharField(blank=True, choices=[('HOMEM_CIS', 'Homem cis'), ('MULHER_CIS', 'Mulher cis'), ('HOMEM_TRANS', 'Homem Trans'), ('MULHER_TRANS', 'Mulher Trans'), ('NAO_BINARIO', 'Não-binário'), ('AGENERO', 'Agênero'), ('GENERO_FLUIDO', 'Gênero fluido'), ('OUTRO', 'Outro'), ('NAO_INFORMAR', 'Prefiro não informar')], max_length=30, null=True),
        ),
    ]
