# Generated by Django 5.1.14 on 2025-11-09 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(help_text='Digite um CEP válido no formato 00000-000 ou 00000000.', max_length=9, validators=[django.core.validators.RegexValidator(message='Digite um CEP válido no formato 00000-000 ou 00000000.', regex='^\\d{5}-?\\d{3}$')])),
            ],
        ),
    ]
